L = "https://charlescheung96.github.io" # <head> 里面的 baseurl 信息，填你的博客地址
title = "Charles' Blog" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
#theme = "mogege" # 主题 (需要自己下载)
theme = "LoveIt"
publishDir = "docs"

paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt
# googleAnalytics = "" # Google 统计 id

preserveTaxonomyNames = true

[taxonomies]
  tag = "tags"
  category = "categories"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
  posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "全部文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[params]
    # LoveIt 主题版本
    version = "0.2.X"
    since = 2021
    author = "charles"                          # Author's name
    #avatar = "/images/me/avatar.png"           # Author's avatar
    subtitle = "Just for Fun"                  # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    enableGitalk = true # gitalk 评论系统

    google_verification = ""

    description = "" # (Meta) 描述
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "xxoo"
    Twitter = "xxoo"
    Email   = "xxoo"
    Instagram = "xxoo"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    Facebook = "xxoo"
    Telegram = "xxoo"
    Dribbble = "xxoo"
    Medium = "xxoo"

# 应用图标配置
[params.app]
   # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
   title = "Charles' web Blog"
   # 是否隐藏网站图标资源链接
   noFavicon = false
   # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
   svgFavicon = ""
   # Android 浏览器主题色
   themeColor = "#ffffff"
   # Safari 图标颜色
   iconColor = "#5bbad5"
   # Windows v8-10 磁贴颜色
   tileColor = "#da532c"

# 搜索配置
[params.search]
   enable = true
   # 搜索引擎的类型 ("lunr", "algolia")
   type = "algolia"
   # 文章内容最长索引长度
   contentLength = 4000
   # 搜索框的占位提示语
   placeholder = ""
   # 最大结果数目
   maxResultLength = 10
   # 结果内容片段长度
   snippetLength = 50
   # 搜索结果中高亮部分的 HTML 标签
   highlightTag = "em"
   # 是否在搜索索引中使用基于 baseURL 的绝对路径
   absoluteURL = false
   [algolia]
     index = "index.zh-cn"
     appID = "PASDMWALPK"
     searchKey = "b42948e51daaa93df92381c8e2ac0f93"

[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = "" # Your client ID
    clientSecret = "" # Your client secret
    repo = "" # The repo to store comments
    owner = "" # Your GitHub ID
    admin= "" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

